### ISSUE TITLE
Disable automatic update of Play Store content

### ISSUE THREAD

**Issue by flodolo** [mozilla-releng/mozapkpublisher#204]
CC @delphine @lwa-moz

Marketing wants to own updating the content on Play Store. In the future we might plug in an external vendor, and need to figure out the API permissions, but for now we want to disable the automatic update from stores_l10n as part of the apk upload.

**Comment by JohanLorenzo** [comment]
Thanks for filing this issue, @flodolo! Some in-tree changes is also needed. I'm going to track this issue in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1560876
