### ISSUE TITLE
Voluptuous a now a non-dev requirement

### ISSUE THREAD

**Issue by nthomas-mozilla** [mozilla-releng/mozapkpublisher#56]
voluptuous is used in the call to check_translations_schema() in PushAPK.run(), but isn't present in requirements.txt. It is in requirements-dev.txt.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1461227.

**Comment by JohanLorenzo** [comment]
Thanks for the catch! I just updated the file with what we run on the production instance. This is now fixed!
