### ISSUE TITLE
Enable pyup

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/mozapkpublisher#64]
Per the RelEng Python Standards (https://wiki.mozilla.org/ReleaseEngineering/Python_Standards), we should have automatic dependency updates enabled for this repo.

If this is deployed anywhere (I don't think it is?), we should update the deployed dependencies, too.

**Comment by mraza007** [comment]
Hey Can I help you with this issue

**Comment by mozbhearsum** [comment]
Thank you for the offer, but I don't think this is something that's a great fit because it requires admin access to the repository.

**Comment by mozbhearsum** [comment]
It looks like this was done at some point!
