### ISSUE TITLE
port to v3 of the google play developer API

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/mozapkpublisher#67]
We're using v2 at the moment, should probably look at porting to v3.
Doc for v3 is at https://developers.google.com/android-publisher/#publishing, v2 at https://developers.google.com/android-publisher/archive/v2/

**Comment by lundjordan** [comment]
@JohanLorenzo - is this something we should prioritize?

@jcristau - what do we gain? What happens if we don't do it?

**Comment by JohanLorenzo** [comment]
I'm not aware of a planned deprecation of the v2 API. I'd say: let move to v3 (or above) whenever v2 is deprecated or whenever we need some bits of data that is not exposed by the v2 API. How does that sound?

**Comment by lundjordan** [comment]
makes sense. wfm

**Comment by JohanLorenzo** [comment]
> I'm not aware of a planned deprecation of the v2 API.

It turns out there was this blog post[1], which was released 3 days before my comment 😅 

API v2 will be decommissioned on December 1st, 2019.

[1] https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html
